### ISSUE TITLE
Cannot create new quiz in a course

### ISSUE THREAD

**Issue by nhoobin** [catalyst/moodle-quizaccess_seb#100]
```
Debug info: SELECT id,course FROM {course_modules} WHERE id IS NULL
[array (
)]
Error code: invalidcoursemodule 
```

**Comment by lucaboesch** [comment]
The exact output says

Notice: Trying to get property 'id' of non-object in mod/quiz/accessrule/seb/rule.php on line 89

since there isn't any existing id of a not already created module i reckon.

**Comment by nhoobin** [comment]
Correct, it assumes the cmid exists at that step. A new module will not have any database entry on the form at that time.

I'll adjust some of the file handling logic with this too, given a call was made for it to save the cmid reference.

**Comment by lucaboesch** [comment]
Seems to work fine. Thanks!
