### ISSUE TITLE
Required param "cmid" missing

### ISSUE THREAD

**Issue by lucaboesch** [catalyst/moodle-quizaccess_seb#101]
When opening a SEB exam using the "Launch Safe Exam Browser" button, Safe Exam Browser does not launch into the quiz but shows an error.
 
Debug info: 

Error code: missingparam

Stack trace:

line 498 of /lib/setuplib.php: moodle_exception thrown
line 562 of /lib/moodlelib.php: call to print_error()
line 29 of /mod/quiz/accessrule/seb/config.php: call to required_param()

**Comment by nhoobin** [comment]
Thanks for catching that, I've adjusted the output link to use a get query such that the cmid will be picked up now.

**Comment by lucaboesch** [comment]
Seems to work fine. Thanks!

**Comment by mohdq2002** [comment]
Hallo,

I have the same issue, could you please let me know how did you solve the problem? thanks a lot

urs

**Comment by dmitriim** [comment]
@mohdq2002 that should be solved ages ago. If you still have the issue please make sure you use the latest code. If so, them please provide full info about replicating the issue including moodle version and all steps.

**Comment by mohdq2002** [comment]
Hallo @grantm dmitriim,
thanks for your reply.

i am using the version Moodle 3.9+ (Build: 20200704)

I am not a Profi in the inspect tool, so i dont know whot do you mean with code and where i have to find.

But maybe these script can help:
-----------------------------------------

document.querySelector("#region-main > div > div.box.py-3.quizattempt > div:nth-child(2) > div:nth-child(2)")
-------------------------------------------
<button type="submit" class="btn btn-secondary" id="single_button5f311498d13535" title="">Safe Exam Browser starten</button>
---------------------------------------------
<button type="submit" class="btn btn-secondary" id="single_button5f311498d13535" title="">Safe Exam Browser starten</button>
-------------------------------------------
#single_button5f311498d13535
---------------------------------------------
document.querySelector("#single_button5f311498d13535")
-------------------------------------------------------
//*[@id="single_button5f311498d13535"]
-----------------------------------------------------------
/html/body/div[2]/div[2]/div[2]/div/section/div/div[3]/div[1]/div[2]/form/button
------------------------------------------------------

view.php?id=115:86 Mixed Content: The page at 'https://pruefungen.wwbildungswerk.de/mod/quiz/view.php?id=115' was loaded over a secure connection, but contains a form that targets an insecure endpoint 'sebs://pruefungen.wwbildungswerk.de/mod/quiz/accessrule/seb/config.php'. This endpoint should be made available over a secure connection.
-------------------------------------------------------------

thanks a lot

yours

**Comment by dmitriim** [comment]
If you are using Moodle 3.9+ then please raise a tracker. This plugin is only for 3.7 and 3.9

**Comment by mohdq2002** [comment]
Hallo @grantm ,
thanks a lot, but do you mean  User support - Work Tracker? [this](https://moodle.org/plugins/mod_tracker)?
urs

**Comment by dmitriim** [comment]
No. I mean https://tracker.moodle.org

**Comment by rajtech12** [comment]
When opening a SEB exam using the "Launch Safe Exam Browser" button, Safe Exam Browser does not launch into the quiz also doesn't show an error.


It complete display a dark black blank screen for 2 second and revert back to the last screen.
