### ISSUE TITLE
Add data from quizaccess_seb_template to privacy data provider

### ISSUE THREAD

**Issue by dmitriim** [catalyst/moodle-quizaccess_seb#116]

**Comment by nhoobin** [comment]
I think we should also look at the data deletion functions as they impact the usability of the plugin itself.

As per https://docs.moodle.org/dev/Privacy_API#Delete_personal_information_for_a_specific_user_and_context.28s.29 
`All attempts should be made to delete this data where practical while still allowing the plugin to be used by other users. `

Currently this wipes entire records in quizaccess_seb_quizsettings. The plugin doesn't work once those records are removed. I wouldn't think that the usermodified would warrant deleting everything. Such that I haven't added this in for the templates.

**Comment by dmitriim** [comment]
Good point. Maybe we can just replace userids with 0
