### ISSUE TITLE
Locked SEB settings in case of "Yes - use SEB client config"

### ISSUE THREAD

**Issue by lehrem** [catalyst/moodle-quizaccess_seb#123]
![locked_SEB_settings](https://user-images.githubusercontent.com/60661112/74160623-fd8f2200-4c1d-11ea-8b6c-4370a0bfa9b0.PNG)
1. As a teacher: Choose "Yes - use SEB client config" in the quiz settings.
2. Solve quiz with SEB as a student
3. As a teacher: Navigate to the quiz settings. All SEB settings are locked (what is okay) but viewable (NOT ok). See attached screenshot.

Requirement: The teacher should only see the locked manual SEB settings when the quiz is set to "Yes - configure manually". The teacher should only see the locked SEB settings that really apply to the quiz.

**Comment by lucaboesch** [comment]
Good catch!
Maybe you could specify the issue's title to 

Locked SEB settings in case of "Yes - use SEB client config"

which would make it some more distinguishable.

**Comment by lehrem** [comment]
Successfully tested on Catalyst Moodle with SEB 3.0 on Windows.

**Comment by lehrem** [comment]
Successfully tested
