### ISSUE TITLE
Integrate plugin code to Moodle

### ISSUE THREAD

**Issue by dmitriim** [catalyst/moodle-quizaccess_seb#13]
As the final task of the project we would like to integrate the plugin to moodle code base.
- [x] Create Moodle tracker
- [x] Remove travis file
- [x] Fix cbit complains
- [x] Remove an experimental setting
- [x] Remove an old core plugin
- [x] Testing instructions
- [x] Documentation

**Comment by nhoobin** [comment]
For reference in the comments, the tracker URL is https://tracker.moodle.org/browse/MDL-67850

**Comment by dmitriim** [comment]
Done as part of 

https://tracker.moodle.org/issues/?jql=labels%20%3D%20SEBDeeperIntegration
