### ISSUE TITLE
No need to enrol in the course when self enrolment without password is activated

### ISSUE THREAD

**Issue by lehrem** [catalyst/moodle-quizaccess_seb#131]
1. Download the config.seb file from the quiz starting page.
2.  Doubleclick the config.seb file
3. SEB starts in the configuration which is defined in config.seb. The SEB start URL is a direct link to the quiz in Moodle.
4. Log in to Moodle as a student
5. The student has to enrol in the course (see attached screenshot)

Requirement: There shouldn't be an enrolment since the self enrolment without password in the course is activated and the referred quiz is a QRSEB quiz. The student should be automatically enroled in the course and land directly on the quiz starting page.
![Enrolment](https://user-images.githubusercontent.com/60661112/74242998-2e835b80-4cdf-11ea-8e0b-a86068d3be10.PNG)

**Comment by nhoobin** [comment]
When visiting a quiz starting page the require_login() function is called to check enrolment status. This redirects to the enrolment page if a used is not enrolled. 

The requirement (SA10/ST8) is a unique use-case which deviates how the enrolment plugins and flow operate. What changes I could make to core may be rejected. 

Core changes could be:
* Adding a hook to the require_login function
* Modifying the quiz view page
* Modifying the self enrolment plugin with an exception for SEB
 
We think that it's not a clean architecture to have this functionality this way, and could couple a custom plugin and this quiz_accessrule together for this specific requirement.

I suggest we could encapsulate the required flow in a local helper plugin which could enrol the student and redirect them back to the correct quiz landing page. This would not be part of core, but an external plugin to resolve this requirement.

**Comment by isacsonk** [comment]
I talked with one of our online exam experts and he thinks it is ok, if the students have to click the enroll button. Of course it would have been nice to have an automatic enrollment but we can live with one click more. Since Marco told me that our online exam expert could decide in this matter, I suggest we set this issue to won't fix. @lucaboesch: please comment if this is ok with you as well.

**Comment by lucaboesch** [comment]
Having that extra enroll button click is totally all right with me.
Best,
Luca

**Comment by dmitriim** [comment]
As an alternative solution auto enrol plugin could be used https://moodle.org/plugins/enrol_autoenrol
