### ISSUE TITLE
closed/secure environment on quiz starting page

### ISSUE THREAD

**Issue by lehrem** [catalyst/moodle-quizaccess_seb#132]
1. Download the config.seb file from the quiz starting page.
2. Doubleclick the config.seb file
3. SEB starts in the configuration which is defined in config.seb
4. Log in to Moodle as a student and navigate to the quiz starting page of a QRSEB quiz.
5. There are a lot of links on the  starting page that allow the student to navigate away (see attached screenshot).

Requirement: Students land on the quiz starting page in a closed/secure environment, so that the student is not able to navigate somewhere else in Moodle and read information he is not supposed to access before the exam. Links in the breadcrumb and link to the personal profile and log out should be deactivated as well as the links to the previous/following activities and the links in the "Jump to..." menu. 

![Quiz_Start_Page](https://user-images.githubusercontent.com/60661112/74246724-465dde00-4ce5-11ea-8c96-eddd0cb94103.PNG)

**Comment by isacsonk** [comment]
ok, no links anymore on the quiz starting page
