### ISSUE TITLE
closed/secure environment after submitting a quiz

### ISSUE THREAD

**Issue by lehrem** [catalyst/moodle-quizaccess_seb#133]
1. Download the config.seb file from the quiz starting page.
2. Doubleclick the config.seb file
3. SEB starts in the configuration which is defined in config.seb
4. Log in to Moodle as a student and attempt a QRSEB quiz.
5. Submit the quiz.
6. The page that appears after submission is not a closed environment. There are a lot of links on the starting page that allow the student to navigate away (Please see screenshot).

Requirement: After submitting a QRSEB quiz, students land in a closed/secure environment, so that the student is not able to navigate somewhere else in Moodle and read information he is not supposed to access before the exam. Links in the breadcrumb and link to the personal profile and log out should be deactivated as well as the links to the previous/following activities and the links in the "Jump to..." menu.
Moodle-Blocks should still be visible if they are configured to appear on the page that appears after submitting a Moodle quiz.

![Page_after_Submission](https://user-images.githubusercontent.com/60661112/74247521-79ed3800-4ce6-11ea-9fea-966fcf113f40.PNG)

**Comment by nhoobin** [comment]
This is linked to the pull request #132

**Comment by isacsonk** [comment]
Tested on win with SEB 3.0 --> block is now shown after submitting the quiz, which is good. 
(But block is also shown before starting the quiz, there it should not be shown, see #166, but since the issue is open it probably just hasn't been addressed yet)
