### ISSUE TITLE
Name of student vanishes while solving a quiz

### ISSUE THREAD

**Issue by lehrem** [catalyst/moodle-quizaccess_seb#136]
1. Log in to Moodle as a student and attempt a QRSEB quiz with Safe Exam Browser.
2. While solving the quiz: The firstname and surname of the student is not viewable in the top right corner.

Requirement: Name of the student must be viewable since examiner should be able to see with what account a student is writing the exam. Place no link on the name.

**Comment by lehrem** [comment]
Another Requirement:  Student should be able to change language when solving a QRSEB quiz.

**Comment by dmitriim** [comment]
Created https://tracker.moodle.org/browse/MDL-68009

**Comment by lucaboesch** [comment]
I was just reading the comment by Tim Hunt in https://tracker.moodle.org/browse/MDL-68009?focusedCommentId=784244&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-784244. Well, he has a point. But also Marco does.

See, 'Name of student vanishes' is not entirely correct. It is not in the top right user menu place, but that is not what is promised (it's what Marco expected, though).
The help text for 'show the user's picture' says 'If enabled, a student's name and picture will be shown on-screen during the attempt, and on the review screen, making it easier to check that the student is logged in as themselves in an invigilated (proctored) exam.'.
And it is shown, but that's on the quiz navigation and the review screen.
It works with either a small or large image.

![Userimageandname](https://user-images.githubusercontent.com/377279/75122200-918bcf80-569b-11ea-96d5-f70249a6b532.png)

I think it could be debated whether this is a bug.

**Comment by dmitriim** [comment]
@lucaboesch  interesting that I just figured it out the same moment you posted this message :)

**Comment by dmitriim** [comment]
There is another issue here as we land students to the secure mode before actually starting and after finishing the attempt. These pages do not use quiz navigation.

**Comment by dmitriim** [comment]
For reference, I have raised https://tracker.moodle.org/browse/MDL-68041

**Comment by dmitriim** [comment]
Integrated as part of https://tracker.moodle.org/browse/MDL-68041
