### ISSUE TITLE
No “Exit safe exam browser” button

### ISSUE THREAD

**Issue by dmitriim** [catalyst/moodle-quizaccess_seb#137]
1. Configure a SEB quit link (Yes - Configure manually)
2.  Start a QRSEB quiz attempt and then submit it.
3.  There is no button “Exit safe exam browser” showing up.

Requirement: There should be a button “Exit safe exam browser” with the SEB quit link and SEB closes when clicking on the button.

**Comment by danschlet** [comment]
The button doesn't work correctly, because a question mark "?" is added to the quit URL.

**Comment by isacsonk** [comment]
ok, tested on windows using seb 3.0
