### ISSUE TITLE
Uploaded SEB file is lost when duplicate an activity

### ISSUE THREAD

**Issue by dmitriim** [catalyst/moodle-quizaccess_seb#147]
Steps to replicate:

1. Create a new quiz and enable usage of SEb as Upload own config file.
2. Upload file and save the settings.
3. Duplicate the quiz.
4. Go and edit just copied quiz.

Expected: uploaded file is in the file area.

Actual result: no file is in the file area.

**Comment by isacsonk** [comment]
not ok, I tried to duplicate a quiz (https://seb-demo.catalyst-au.net/mod/quiz/view.php?id=51) with an uploaded config and received an error message:
![image](https://user-images.githubusercontent.com/7068702/75477838-301a7800-599d-11ea-82a6-172d04f9113d.png)

**Comment by dmitriim** [comment]
Hi @isacsonk 
Looks like it's a regression and it used to work before. Back to dev...

**Comment by dmitriim** [comment]
Wil lbe fixed as part of #193
