### ISSUE TITLE
Restrict access to a quiz by Config key

### ISSUE THREAD

**Issue by dmitriim** [catalyst/moodle-quizaccess_seb#15]
Restrict access to a quiz if
- [x] Require the use of Safe Exam Browser is enabled, but accessed not in SEB session without bypass capabilities 
- [x] HTTP header "X-SafeExamBrowser-ConfigKeyHash" in SEB is not equal generated config key hash in Moodle
- Respect quizaccess/seb:bypassseb
- [x] Trigger an event see https://github.com/catalyst/moodle-quizaccess_seb/issues/8

**Comment by andrewmadden** [comment]
Will leave triggering the event until Issue #8 is finished. Will leave TODO in code.
