### ISSUE TITLE
Missing examSessionClearCookiesOnStart = false in config.seb file

### ISSUE THREAD

**Issue by lehrem** [catalyst/moodle-quizaccess_seb#155]
1. Create a quiz
2. Set "Require the use of Safe Exam Browser" to "Yes - configure manually"
3. As a Student: Navigate to quiz and download config.seb file to desktop.
4. Open config.seb file with an editor
5. I can't find the examSessionClearCookiesOnStart = false (For 'yes - configure manually option) tag in the config.seb file.

Requirement: The tag examSessionClearCookiesOnStart = false should be part of each config.seb file if the quiz is set to "Yes - configure manually".

**Comment by isacsonk** [comment]
ok, examSessionClearCookiesOnStart = false is included in the xml-file
