### ISSUE TITLE
Uploading config file to add a new template doesn't work

### ISSUE THREAD

**Issue by isacsonk** [catalyst/moodle-quizaccess_seb#161]
How to reproduce:

1. login as an admin an go to https://seb-demo.catalyst-au.net/mod/quiz/accessrule/seb/template.php
2. click "add new template"
3. upload a config file created in the SEB Config Tool 
--> Uploading takes forever, when it is finished I receive a message "Data submitted is invalid"

![image](https://user-images.githubusercontent.com/7068702/74750484-11fd9b00-526c-11ea-8b76-dccedf58b598.png)

Requirement:
Uploading a config file created in the config tool should work. Uploading should only take 1-3 seconds.

Remarks:
- Marco tried to upload the file and he doesn't get an error but also the upload never finishes.
- This has nothing to do with the template, but also uploading images in a question takes a very long time.

**Comment by dmitriim** [comment]
It feels like some issues with the demo infrastructure and not the code itself. We will have a look.

**Comment by isacsonk** [comment]
Uploading a config file from home went very quick today. And I might have received the Data submitted invalid message because I missed to change the setting from configuring a client to starting an exam the other day. I'll try to upload a file from the office on Monday and if this works fine, I'll close the issue then.

**Comment by isacsonk** [comment]
Uploading works now therefore I closed the issue.
