### ISSUE TITLE
Question mark is added to seb quit link

### ISSUE THREAD

**Issue by lehrem** [catalyst/moodle-quizaccess_seb#165]
1. As a Student: Log in to Moodle and navigate to quiz at URL https://seb-demo.catalyst-au.net/mod/quiz/view.php?id=13
2. Click on "Download configuration" button and download seb config file to desktop.
3. Open seb config file. SEB launches.
4. Solve quiz at https://seb-demo.catalyst-au.net/mod/quiz/view.php?id=13 as a student
5. Submit quiz
6. Click on "exitsebbutton" that is displayed on the page that appears after submitting the quiz.
7. SEB does not close.

Requirement: The link that is placed on the "exitsebbutton" must be the same link as in the config.seb file. There is a question mark "?" added to the URL and that is the reason why SEB does not quit.

**Comment by isacsonk** [comment]
Did you retest the testcase after the fix? Because I tried to reproduce the issue, but I fail in step 3. I receive a black page when SEB launches and those cannot do the steps 4-7.

**Comment by isacsonk** [comment]
Ok, Marco tells me, it works on his device. I will have to check if SEB has a problem on the Fujitsu device I was testing on.

**Comment by isacsonk** [comment]
ok, tested on windows using seb 3.0
