### ISSUE TITLE
Blocks appear on quiz starting page

### ISSUE THREAD

**Issue by lehrem** [catalyst/moodle-quizaccess_seb#166]
1. As a Student: Log in to Moodle and navigate to quiz at URL https://seb-demo.catalyst-au.net/mod/quiz/view.php?id=13
2. Click on "Download configuration" button and download seb config file to desktop.
3. Open seb config file. SEB launches.
4. As a Student: Navigate to quiz starting page at https://seb-demo.catalyst-au.net/mod/quiz/view.php?id=13
5. There is a block "Evaluation" appearing on the right that contains a link.

Requirement: No blocks should be visible on the starting page of a QRSEB quiz when the user is in the role "student". Students should be in a closed/secure environment.

Please note: Blocks must be visible (if configured so) on the page that appears after submitting the quiz since we would like to show the link to the exam evaluation directly after the student submitted the exam. The personal link to the evaluation is in a block.

**Comment by lucaboesch** [comment]
You're right, Marco.
I may add
**unless** you explicitely configure the blocks to appear so in the setting 
<img width="405" alt="grafik" src="https://user-images.githubusercontent.com/377279/74826167-6e63c780-530b-11ea-8116-1de002f0ded1.png">
That's a popular thing to do, to allow a resource this way.

**Comment by lucaboesch** [comment]
Sorry I closed by mistake!
Please re-open.
Thanks.

**Comment by lehrem** [comment]
Please reopen. I don't have the rights neither.

**Comment by dmitriim** [comment]
I have added two new settings to allow admins to control blocks for SEB quizzes.

- Display blocks before quiz started
- Display blocks after quiz finished


![image](https://user-images.githubusercontent.com/4626431/75208403-aa959d00-57cf-11ea-9bc6-b46a2bcfc00f.png)

**Comment by isacsonk** [comment]
ok, tested on windows using seb 3.0 block is not displayed on the starting page anymore
