### ISSUE TITLE
don't display field "allowed Browser Keys" if "Yes-Configure manually is selected" 

### ISSUE THREAD

**Issue by isacsonk** [catalyst/moodle-quizaccess_seb#177]
As a teacher go to quiz settings and at "Require the use of Safe Exam Browser" select "Yes -Configure
manually" 
The last field "allowed Browser Keys" only really makes sense if you upload a config file, since you have to copy the browser key from the config tool into this field.
I suggest to not display it for this setting.

**Comment by isacsonk** [comment]
At the ETH we all agree, that this field should not be displayed, also not if "Yes-Use an existing template" is chosen (see #178). 
For the setting "Yes-upload my own config" we would suggest the field is included with a hint, that the user has to be aware of, that if he changes the password in Moodle, the before inserted Browser key from the config tool is not valid anymore. 
It is up to Luca to decide if he agrees with this or if he wants to keep the field everywhere. So please @lucaboesch comment your decision when you have decided.

**Comment by lucaboesch** [comment]
After some deliberation I come to the same conclusion, @isacsonk.
The wording could be: "If you change some SEB setting in Moodle after having copied the browser exam key from the SEB Config tool, the key will no longer be valid."
I agree to remove the Browser exam key field for the "Yes–Use an existing template" scenario.
Best,
Luca

**Comment by isacsonk** [comment]
ok, the field is not displayed anymore
