### ISSUE TITLE
don't display field "allowed Browser Keys" if "Yes-Use an existing template" is selected

### ISSUE THREAD

**Issue by isacsonk** [catalyst/moodle-quizaccess_seb#178]
As a teacher go to quiz settings and at "Require the use of Safe Exam Browser" select "Yes -Use an existing template"
The teacher probably is not the one who has created the template, therefore he cannot look up the exam key in the config tool to use this field. And also if he asked the Moodle admin for the exam key, as soon as he would change the Password in the Moodle exam settings the exam key in the template would not be the same anymore as the one he received from the Moodle admin. 

Therefore I suggest to not display this field for this setting.

**Comment by dmitriim** [comment]
Hi @isacsonk . There was a specific requirement to have "allowed Browser Keys" as an additional restriction to all ways of SEB usage. Could you please double check with the rest of the team if your suggestion is accepted by everyone. Thanks!

**Comment by isacsonk** [comment]
Hi @dmitriim: sometimes you don't realize what makes sense and what might not until you are testing, sorry for confusing requirements. I've checked with my ETH team mates see comment at issue 177, but since Luca has a different scenario as us, it is important to wait for his response also.

**Comment by dmitriim** [comment]
@isacsonk it's all good. No worries. :)

**Comment by isacsonk** [comment]
ok, field is not displayed anymore.
