### ISSUE TITLE
ETH Scenario with templates assumes direct landing on safe start quiz page

### ISSUE THREAD

**Issue by isacsonk** [catalyst/moodle-quizaccess_seb#188]
how to reproduce
------------------------
As a Moodle setting change capabilites for the teacher so that SEB Settings are only allowed for the Moodle Admin not for the teacher
also in the SEB Acces rules only SEB-Link is selected not the https-Link
then add a template by uploading a config file configured to allow the use of excel
go to the quiz created by the teacher, configure the quiz to use this template
Install SEB and create a config file which has a start url leading to this exam 
As a student start SEB on the client, you have to login and then you land on the page with the Launch Safe Exam Browser button, if you click on the button SEB is reconfigured and you land on the page with the button "Attempt quiz". This is the way how it works now.

requirement
-----------------
If you look at the ETH Scenario this "inbetween" page with the Launch SEB button is an extra step not anticipated in the ETH scenario. Since you already have a SEB installed it would be much more user friendly, if Moodle would realize that you are coming with SEB, that the quiz is configured with an existing template, reconfiguring is therefore taken place as soon as you navigate to the quiz and the student lands directly on the quiz attempt page.

remark
----------
Is it possible to do an improvement here, so that the process would fit the ETH scenario here more? That is: if you come with SEB you go directly to the quiz. If you come with a normal browser you land on the Launch SEB button page.

**Comment by dmitriim** [comment]
This should be covered by https://github.com/catalyst/moodle-quizaccess_seb/issues/189
