### ISSUE TITLE
If you come with SEB and NOT with a normal browser you should directy land on the safe start quiz page with button "attempt quiz"

### ISSUE THREAD

**Issue by isacsonk** [catalyst/moodle-quizaccess_seb#189]
how to reproduce
------------------------

1. As a Moodle setting change capabilites for the teacher so that SEB Settings are only allowed for the Moodle Admin not for the teacher
2. also in the SEB Acces rules only SEB-Link is selected not the https-Link
3. then add a template by uploading a config file configured to allow the use of excel
4. go to the quiz created by the teacher, configure the quiz to use this template
5. Install SEB and create a config file which has a start url leading to this exam 
6. As a student start SEB on the client, you have to login and then you land on the page with the Launch Safe Exam Browser button, if you click on the button SEB is reconfigured and you land on the page with the button "Attempt quiz". This is the way how it works now.

requirement
-----------------
If you look at the ETH Scenario this "inbetween" page with the Launch SEB button is an extra step not anticipated in the ETH scenario. Since you already have a SEB installed it would be much more user friendly, if Moodle would realize that you are coming with SEB, that the quiz is configured with an existing template, reconfiguring is therefore taken place as soon as you navigate to the quiz and the student lands directly on the quiz attempt page. If you are coming with SEB you should always (also for config manually and upload manually directly land on the "attempt quiz" page and SEB should automatecally be reconfigured)

remark
----------
Is it possible to do an improvement here, so that the process would fit the ETH scenario here more? That is: if you come with SEB you go directly to the quiz. If you come with a normal browser you land on the Launch SEB button page.

**Comment by isacsonk** [comment]
I talked to Marco about this issue, if you come with SEB it would be userfriendly and consistent that always SEB is reconfigured if there is a configuration file, a template or config manually configured in the quiz settings automatically and you land directly on the "attempt quiz" page

**Comment by danschlet** [comment]
Implementation suggestion:

- When the quiz start page is loaded, check if the browser has the string "SEB" in its user agent.
- If yes, load the sebs:// link automatically (forward to it?), same as if the user would have clicked the "Launch SEB" button

**Comment by dmitriim** [comment]
Should this feature interact with "Show Safe Exam Browser config links" setting. E.g. if "Show seb:// link" is disabled. 
I'd suggest to have this feature configurable to be able to on/off it if required.

**Comment by isacsonk** [comment]
@dmitriim: good idea to make it configurable. If you come with SEB and if "Show seb:// link" is disabled then SEB is reconfigured if the quiz setting is set to template, config file or config manually and you land directly on the "attempt quiz" page.
I suggest to add an explanation after: "Decide whether to show links for the user to access the Safe Exam Browser configuration file when access to quiz is prevented. Note that seb:// links may not work for every browser."
something like:
"If you disable "Show seb:// link" and navigate to the quiz using the Safe Exam Browser, the Safe Exam Browser configuration file is automatically loaded, Safe Exam Browser is reconfigured and the "attempt quiz" button is displayed."

**Comment by dmitriim** [comment]
@isacsonk We have pushed this feature to DEMO site and it will be available for testing in a couple of hours.

There is a new admin setting to enable this feature: 
![image](https://user-images.githubusercontent.com/4626431/77621214-1e25f800-6f90-11ea-8c69-c34aaa9aced8.png)

Please test. Once tested we will pull the code to the integration branch.

**Comment by isacsonk** [comment]
tested on catalyst server --> ok
