### ISSUE TITLE
import/restore of a course with a quiz with a uploaded config throws an error

### ISSUE THREAD

**Issue by isacsonk** [catalyst/moodle-quizaccess_seb#193]
how to reproduce
--------------------

1. login as an admin
2. create a a course
3. create a quiz using SEB with your own config uploaded
4. backup the course
5. restore the course
6. an error is displayed: "No uploaded SEB config file could be found for quiz with cmid: [##]"

as admin create a course
import a quiz, with uploaded config https://seb-demo.catalyst-au.net/mod/quiz/view.php?id=20 from course  https://seb-demo.catalyst-au.net/course/view.php?id=4
the same error is displayed: "No uploaded SEB config file could be found for quiz with cmid: [##]"

![image](https://user-images.githubusercontent.com/7068702/75475319-e596fc80-5998-11ea-9343-b126f55dcfc4.png)

requirement
--------------
you should be able to backup and restore or import a course with a quiz with an uploaded config file

**Comment by dmitriim** [comment]
Fixed. Will be available in Demo shortly.

**Comment by isacsonk** [comment]
Tested restore of a course with a quiz configured with uploaded own config --> no error message, restore works. Also the import works now.
