### ISSUE TITLE
remove option yes-Configure manually in the drop down if none of the configurations are allowed

### ISSUE THREAD

**Issue by isacsonk** [catalyst/moodle-quizaccess_seb#195]
How to reproduce
-----------------------
For the teacher set all Safe Exam Browser Access rules to prevent except for 
Bypass the requirement to view quiz in Safe Exam Browser. 
and
Modify Safe Exam Browser quiz setting: Require Safe Exam Browser.
--> as a teacher you see following in the quiz settings:
No
Yes- Configure manually
Yes- Use SEB client config
![image](https://user-images.githubusercontent.com/7068702/75681720-753bf400-5c94-11ea-9570-ce4438d8454d.png)

Requirement
----------------
Since you have removed all the capabilities to configure manually it doesn't make much sense to show the selection "Yes- Configure manually"
if all possibilities to configure manually have been removed, "Yes- Configure manually" should be removed in the drop-down of "Require the use of SEB"

**Comment by dmitriim** [comment]
@isacsonk Good one!

**Comment by isacsonk** [comment]
tested --> great, now "Yes- Configure manually" does not turn up anymore, if you have disabled all configuration possibilities for manual configuration for the teacher.
