### ISSUE TITLE
you should be able to allow more than one url

### ISSUE THREAD

**Issue by isacsonk** [catalyst/moodle-quizaccess_seb#196]
how to reproduce
--------------------
as a teacher create a quiz and configure it to be used with "yes-configure manually"
in the field "Expressions allowed" enter two urls that are to be allowed for example:
https://seb-demo.catalyst-au.net/
https://www.tg.ethz.ch/
save
as a student start for example firefox and go to the quiz
click "launch Safe Exam Browser"
--> SEB is reconfigured but you get the message that the url is not allowed

requirement
-------------------
the xml file should have the complete needed syntax also for more than one urls

**Comment by danschlet** [comment]
There is also a bug regarding URL filtering in the current SEB 3.0 for Windows build. Testing URL filtering should only be continued with SEB 3.0 when this bug was fixed.

**Comment by lucaboesch** [comment]
Thanks for letting us know, @danschlet !

**Comment by isacsonk** [comment]
Without the forward slashes at the end of the url's it seems to work. @lucaboesch: Have you retested? Does it work in your case as well?

**Comment by isacsonk** [comment]
After having installed the newest SEB 3.0 version, it also works with the forward slashes at the end of the url.
