### ISSUE TITLE
Place the setting "Suppress Safe Exam Browser download button" directly below the setting "Require the use of Safe Exam Browser"

### ISSUE THREAD

**Issue by lehrem** [catalyst/moodle-quizaccess_seb#202]
1. Create a quiz
2. Set "Require the use of Safe Exam Browser" to "Yes - Upload my own config" OR "Yes - Use an existing template"
3. The setting "Suppress Safe Exam Browser download button" is placed below the uploaded own config or below the drop-down menu with the listed templates, respectively.

Requirement: Place the setting "Suppress Safe Exam Browser download button" directly below the setting "Require the use of Safe Exam Browser" in both cases.

**Comment by dmitriim** [comment]
@lehrem thank you for raising this issue. I'm not sure if this is the best UI here. How about to ask Hina's recommendation about that before changing?

**Comment by dmitriim** [comment]
![image](https://user-images.githubusercontent.com/4626431/75816616-a7129f00-5de9-11ea-8c62-c3ea82be8e54.png)


![image](https://user-images.githubusercontent.com/4626431/75816656-b691e800-5de9-11ea-9b31-e7f786d41b70.png)


![image](https://user-images.githubusercontent.com/4626431/75816700-c9a4b800-5de9-11ea-8c79-9254cdca54c9.png)

**Comment by lehrem** [comment]
What we think: The setting about the SEB download button is a Moodle setting that is placed in between settings that all have something to do with the configuration (file) of SEB. Placing it directly below the setting "Require the use of Safe Exam Browser" would separate the two kinds of settings.

**Comment by dmitriim** [comment]
Cancelled by @lehrem
