### ISSUE TITLE
Change the way to process quiz_settings when switch from Manual to Template or Own config or Seb client.

### ISSUE THREAD

**Issue by dmitriim** [catalyst/moodle-quizaccess_seb#205]
Otherwise some settings are still in DB e.g. Expressions allowed and once you switch back to Manual they are populated.

Not sure about the best way, but some options could be:
 -  delete and then save new record which will get defaults
 - a new method "reset_default" to quiz_settings class and call it when required
 - .....
 - .... 

P.S. We remove records when we switch to No seb so don't need to change that.

**Comment by nhoobin** [comment]
I'm not sure about the first option, as it populates the settings from the form elements.
Anything inside a form, via the $settings variable will be saved to the quiz_settings object.
https://github.com/catalyst/moodle-quizaccess_seb/blob/e5e40f500883182f8d523a84bc04c18fd5f52398/rule.php#L193-L204

**Comment by dmitriim** [comment]
@nhoobin ideas?
