### ISSUE TITLE
display template settings deactivated if only the admin can choose template to be used

### ISSUE THREAD

**Issue by isacsonk** [catalyst/moodle-quizaccess_seb#214]
Precondition
-------------------
The teacher has the capabilities to choose No SEB required , Yes- Use client config and Yes, -use existing template, but he doesn't have the capability to choose which template he wants to use. The teacher does not have the capability set to choose Upload own config or config manually.

Scenario
----------------
The admin uploads several templates
The admin goes to a quiz of teacher a and selects one template for this quiz
The teacher a goes to his quiz. He can now choose whether he wants the quiz to be configured to No, Yes- Use client config, or Yes- Use template
![image](https://user-images.githubusercontent.com/7068702/77343060-6abfc800-6d31-11ea-81c9-df655fb0c296.png)
He chooses Yes- Use a template
Since he cannot choose which template he wants to use the settings Safe Exam Browser config template where the template name is found is displayed deactivated. The teacher sees what the admin has configured but he cannot change it.

For this Scenario there is the need for another capability.
Now we have: Modify Safe Exam Browser quiz setting: Select SEB template.
quizaccess/seb:manage_seb_templateid
this capability controls whether following is displayed
"Require the use of Safe Exam Browser -Yes-Use existing template"
AND
"Safe Exam Browser config template [TEMPLATE NAME]"

If we had another capability, let's say 
Modify Safe Exam Browser quiz setting: Change SEB template
and we set this capability for the teacher to be prevented

The teacher should see in the quiz settings, which template the admin has chosen. The teacher can now change the configuration to require SEB - no and ask his assistant who has the student role to test the quiz. The student than doesn't need to have SEB installed. after the assistant tested the quiz. The teacher can set the setting back to use existing template so that his students need SEB to do the quiz.

Remark
------------
this would be one of the ETH scenarios. Of course for the BYOD scenarios you should still be able to give the teacher all the capabilities so he can choose everything himself for example upload own config or so that he is able to choose which template he wants.

![SEB Template](https://user-images.githubusercontent.com/7068702/77295598-8f428280-6ce6-11ea-90f4-77fc4fde0412.png)

**Comment by dmitriim** [comment]
Hi @isacsonk 
Can you please be more specific about this issue? 

> The teacher does not have the capability set to choose Upload own config or config manually.

What capabilities are you talking about? Is it "quizaccess/seb:manage_seb_templateid"?

That what I can see locally trying to replicate the issue:
![image](https://user-images.githubusercontent.com/4626431/77298442-0ad01e00-6d3f-11ea-9afa-061aee67950e.png)

**Comment by dmitriim** [comment]
Or you'd like us to change existing behaviour?

**Comment by isacsonk** [comment]
@dmitriim : this issue is the proposed solution to Hinas input, that it might be strange if an admin sets a template and the teacher doesn't see what is going on because he doesn't have the capabilities. We discussed this in todays meeting. Maybe Nicolas could also help with the explanation. I tried to edit the description to make it more understandable, I also set the capabilitities on the catalyst server the way I would in the described scenario. 
What would be needed is another capability so that if prevented you are not able to choose another template, the field HK-Test should be deactivated:
![image](https://user-images.githubusercontent.com/7068702/77345039-6052fd80-6d34-11ea-886a-2cda2092a9ba.png)
see settings for https://seb-demo.catalyst-au.net/mod/quiz/view.php?id=102

**Comment by dmitriim** [comment]
Hi @isacsonk 

I have watched the meeting recording and now it makes sense what you are asking for. 

Potentially it's a week or more of dev work as we'd need to rewrite the way how we build the form and respect capabilities for each individual element of the form + potential permissions conflicts. 

In real life how likely will you have a case when an admin has configured to use a template, but a teacher doesn't have permission to use it? A workaround could be if the teacher can contact the administrator and ask to change "locked" quiz?

This work can potentially slow down the integration. Would be good to have some time left to fix possible integration issues and hold on implementing new farures. Also we are way over the budget for this project.

As the code freeze for 3.9 has been extended and we've met the scoped requirements for this project. Our recommendation is to get the current patch into core, as the work that has been done is a defnite improvement. Then if time permits we can revisit these new items.

 Happy to discuss.

**Comment by isacsonk** [comment]
Hi @dmitriim 
Thanks for the information. At ETH this will be as scenario for all Moodle Exams that need a calculator, so it is a real scenario. Anyhow it is possible to do without implementing this. If the teacher changes require SEB to no, the admin has to set it back to use template before the exam starts.
And I think we don't want to risk the integration but I'll discuss this issue with Marco and Thomas and get back to you again.

**Comment by isacsonk** [comment]
Hi @dmitriim: I just talked with Marco about this.
In our opinion
the integration has the highest prio. 
If there is time left. Second prio is: https://github.com/catalyst/moodle-quizaccess_seb/issues/189
And after that if time permits comes this issue #214 as a third prio.

**Comment by dmitriim** [comment]
@isacsonk as the code was integrated to core. If this feature is still required, please raise a new Moodle tracker.

**Comment by isacsonk** [comment]
@dmitriim. Thanks for the reminder. I just discussed it with Marco. We decided not to raise an issue in the Moodle tracker for now. We want to try to gain some experience first and then decide if this feature is needed and in which way it should be solved.
