### ISSUE TITLE
Add default config items to generation of config.

### ISSUE THREAD

**Issue by andrewmadden** [catalyst/moodle-quizaccess_seb#36]
DEFAULT CONFIG SETTINGS
Need to do a little work into figuring out what config should be hard set by Moodle to make the config key works.

- [x] sendBrowserExamKey = true (For all yes options)
- [x] examSessionClearCookiesOnStart = false (For 'yes - configure manually option)
- [x] startUrl

**Comment by dmitriim** [comment]
Not sure if I understand what you mean here.

**Comment by andrewmadden** [comment]
There is a SEB config settings that enables the config key to be sent in the header. If not enabled, we can't check if the config key matches. Does that make sense?

I'm not sure if there are any other settings that must be configured to make sure the Config Key will work.

**Comment by dmitriim** [comment]
ah ok.

**Comment by lehrem** [comment]
I can't find the examSessionClearCookiesOnStart = false (For 'yes - configure manually option) tag in the config.seb file that is provided on the quiz start page.
