### ISSUE TITLE
Seb_linkquitseb should be text field in the settings from

### ISSUE THREAD

**Issue by dmitriim** [catalyst/moodle-quizaccess_seb#54]

**Comment by lucaboesch** [comment]
Has this warning maybe to do with this?
It appears in the edit quiz form

Did you remember to call setType() for 'seb_linkquitseb'? Defaulting to PARAM_RAW cleaning.

line 1389 of /lib/formslib.php: call to debugging()
line 322 of /lib/formslib.php: call to moodleform->detectMissingSetType()
line 228 of /lib/formslib.php: call to moodleform->_process_submission()
line 130 of /course/moodleform_mod.php: call to moodleform->__construct()
line 58 of /mod/quiz/mod_form.php: call to moodleform_mod->__construct()
line 141 of /course/modedit.php: call to mod_quiz_mod_form->__construct()

Best,
Luca

**Comment by lehrem** [comment]
1. Configure a SEB quit link (Yes - Configure manually)
2.  Start a QRSEB quiz attempt and then submit it.
3.  There is no button “Exit safe exam browser” showing up.

Requirement: There should be a button “Exit safe exam browser” with the SEB quit link and SEB closes when clicking on the button.

**Comment by dmitriim** [comment]
Raised #137
