### ISSUE TITLE
A moodle event "security violations by SEB sending wrong hash keys"

### ISSUE THREAD

**Issue by dmitriim** [catalyst/moodle-quizaccess_seb#8]
- [x] Create a prevent_access event.
- [x]  Trigger an event when a student, access the quiz with a different SEB config, which sends a wrong hash key. 
- [x] Trigger an event when access to quiz is prevented by SEB plugin.
- [x]  Following info needs to be included to each event:

-  TBD
- userid
- quizid
- courseid
- module context
- reason string
- page url where it was triggered
- saved config key
- received config key
- TODO saved browser exam keys
- received browser exam key

**Comment by andrewmadden** [comment]
I created a more general `access_prevented` event to capture all reasons that the access to quiz is prevented. 

If need be we can also create a specific event for when the config key exists in header, but does not matched the Moodle config key. E.g. `config_not_matched` or something similar
