### ISSUE TITLE
Clean up data when related quiz is deleted

### ISSUE THREAD

**Issue by dmitriim** [catalyst/moodle-quizaccess_seb#87]
- [x] Use course_delete_module call back (no event listeners in core)
- [x]  Delete DB records
- [x]  Check that all files deleted by course_delete_module

**Comment by nhoobin** [comment]
Just a note that there exists a callback to the quiz_delete_instance() function that implements most of the requested functionality.

https://github.com/catalyst/moodle-quizaccess_seb/blob/cce4f5da3694d0d53bfdad74f7e36fa4a7e60055/rule.php#L243-L259

I'll add something to clean-up the filearea. With some foresight with templates in mind.

**Comment by nhoobin** [comment]
Regarding debugging, when deleting a module via the UI, a webservice is called to delete and most likely async deletion is enabled.

You may not see the hook to `quiz_access_manager::delete_settings($quiz);` in `function quiz_delete_instance` activate.

`course_delete_module` does call the following as an attempt to clean up the module.
```    // Remove all module files in case modules forget to do that.
    $fs = get_file_storage();
    $fs->delete_area_files($modcontext->id);
```
